name: test

channels:
  - conda-forge
  - defaults

dependencies:
  - matplotlib
  - moorpy
  - numpy
  - openmdao > 3.30
  - pyhams
  - pip
  - python
  - pyyaml
  - ruamel.yaml
  - scipy
  - setuptools
  - wisdem>=3.16
  - capytaine
  - gmsh
  - pip:
    - https://github.com/LHEEA/meshmagick/archive/master.zip